var h="function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,g){a!=Array.prototype&&a!=Object.prototype&&(a[c]=g.value)},l="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,n=function(){n=function(){};l.Symbol||(l.Symbol=p)},p=function(){var a=0;return function(c){return"jscomp_symbol_"+(c||"")+a++}}(),r=function(){n();var a=l.Symbol.iterator;a||(a=l.Symbol.iterator=l.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&
h(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return q(this)}});r=function(){}},q=function(a){var c=0;return t(function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}})},t=function(a){r();a={next:a};a[l.Symbol.iterator]=function(){return this};return a},u=function(a){r();var c=a[Symbol.iterator];return c?c.call(a):q(a)},w=function(a){if(a){for(var c=l,g=["Promise"],f=0;f<g.length-1;f++){var d=g[f];d in c||(c[d]={});c=c[d]}g=g[g.length-1];f=c[g];a=a(f);a!=f&&null!=a&&h(c,
g,{configurable:!0,writable:!0,value:a})}};
w(function(a){function c(){this.a=null}function g(b){return b instanceof d?b:new d(function(e){e(b)})}if(a)return a;c.prototype.b=function(b){null==this.a&&(this.a=[],this.f());this.a.push(b)};c.prototype.f=function(){var b=this;this.c(function(){b.i()})};var f=l.setTimeout;c.prototype.c=function(b){f(b,0)};c.prototype.i=function(){for(;this.a&&this.a.length;){var b=this.a;this.a=[];for(var e=0;e<b.length;++e){var a=b[e];b[e]=null;try{a()}catch(m){this.g(m)}}}this.a=null};c.prototype.g=function(b){this.c(function(){throw b;
})};var d=function(b){this.b=0;this.g=void 0;this.a=[];var e=this.c();try{b(e.resolve,e.reject)}catch(k){e.reject(k)}};d.prototype.c=function(){function b(b){return function(c){a||(a=!0,b.call(e,c))}}var e=this,a=!1;return{resolve:b(this.o),reject:b(this.f)}};d.prototype.o=function(b){if(b===this)this.f(new TypeError("A Promise cannot resolve to itself"));else if(b instanceof d)this.s(b);else{a:switch(typeof b){case "object":var a=null!=b;break a;case "function":a=!0;break a;default:a=!1}a?this.m(b):
this.i(b)}};d.prototype.m=function(b){var a=void 0;try{a=b.then}catch(k){this.f(k);return}"function"==typeof a?this.u(a,b):this.i(b)};d.prototype.f=function(b){this.j(2,b)};d.prototype.i=function(b){this.j(1,b)};d.prototype.j=function(b,a){if(0!=this.b)throw Error("Cannot settle("+b+", "+a+"): Promise already settled in state"+this.b);this.b=b;this.g=a;this.l()};d.prototype.l=function(){if(null!=this.a){for(var b=0;b<this.a.length;++b)v.b(this.a[b]);this.a=null}};var v=new c;d.prototype.s=function(b){var a=
this.c();b.h(a.resolve,a.reject)};d.prototype.u=function(b,a){var c=this.c();try{b.call(a,c.resolve,c.reject)}catch(m){c.reject(m)}};d.prototype.then=function(b,a){function c(b,a){return"function"==typeof b?function(a){try{e(b(a))}catch(A){g(A)}}:a}var e,g,f=new d(function(b,a){e=b;g=a});this.h(c(b,e),c(a,g));return f};d.prototype.catch=function(b){return this.then(void 0,b)};d.prototype.h=function(b,a){function c(){switch(d.b){case 1:b(d.g);break;case 2:a(d.g);break;default:throw Error("Unexpected state: "+
d.b);}}var d=this;null==this.a?v.b(c):this.a.push(c)};d.resolve=g;d.reject=function(b){return new d(function(a,c){c(b)})};d.race=function(a){return new d(function(b,c){for(var d=u(a),e=d.next();!e.done;e=d.next())g(e.value).h(b,c)})};d.all=function(a){var b=u(a),c=b.next();return c.done?g([]):new d(function(a,d){function e(b){return function(c){f[b]=c;k--;0==k&&a(f)}}var f=[],k=0;do f.push(void 0),k++,g(c.value).h(e(f.length-1),d),c=b.next();while(!c.done)})};return d});
function x(){window.performance.mark("gapi_load_end");window.performance.measure("gapi_load","gapi_load_start","gapi_load_end");y()}var y,z=null;
function B(){if(z)return z;window.performance.mark("gapi_load_start");var a=window.colabExperiments&&window.colabExperiments.first_party_auth;return z=new Promise(function(c,g){y=c;window.gapi_onload=function(){a?y():gapi.load("auth:client",x)};var f=document.createElement("script");f.src="https://apis.google.com/js/client.js";f.async=!0;f.onerror=function(){g(Error("Error loading "+f.src))};c=document.getElementsByTagName("script")[0];c.parentNode.insertBefore(f,c)})}window.colab_gapi_loader={};
window.colab_gapi_loader.load=B;B().then(function(){},function(){});
