/*

The MIT License (MIT)

Copyright (c) 2014 Guillermo Rauch


Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE. Socket.IO v2.1.1
 (c) 2014-2018 Guillermo Rauch
 Released under the MIT License.
 https://mths.be/utf8js v2.1.2 by @mathias */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(f,d,b){f!=Array.prototype&&f!=Object.prototype&&(f[d]=b.value)};$jscomp.getGlobal=function(f){return"undefined"!=typeof window&&window===f?f:"undefined"!=typeof global&&null!=global?global:f};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.Symbol=function(){var f=0;return function(d){return $jscomp.SYMBOL_PREFIX+(d||"")+f++}}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var f=$jscomp.global.Symbol.iterator;f||(f=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[f]&&$jscomp.defineProperty(Array.prototype,f,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(f){var d=0;return $jscomp.iteratorPrototype(function(){return d<f.length?{done:!1,value:f[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(f){$jscomp.initSymbolIterator();f={next:f};f[$jscomp.global.Symbol.iterator]=function(){return this};return f};$jscomp.iteratorFromArray=function(f,d){$jscomp.initSymbolIterator();f instanceof String&&(f+="");var b=0,a={next:function(){if(b<f.length){var c=b++;return{value:d(c,f[c]),done:!1}}a.next=function(){return{done:!0,value:void 0}};return a.next()}};a[Symbol.iterator]=function(){return a};return a};
$jscomp.polyfill=function(f,d,b,a){if(d){b=$jscomp.global;f=f.split(".");for(a=0;a<f.length-1;a++){var c=f[a];c in b||(b[c]={});b=b[c]}f=f[f.length-1];a=b[f];d=d(a);d!=a&&null!=d&&$jscomp.defineProperty(b,f,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.keys",function(f){return f?f:function(){return $jscomp.iteratorFromArray(this,function(d){return d})}},"es6","es3");
(function(f,d){"object"===typeof exports&&"object"===typeof module?module.exports=d():"function"===typeof define&&define.amd?define([],d):"object"===typeof exports?exports.io=d():f.io=d()})(this,function(){return function(f){function d(a){if(b[a])return b[a].exports;var c=b[a]={exports:{},id:a,loaded:!1};f[a].call(c.exports,c,c.exports,d);c.loaded=!0;return c.exports}var b={};d.m=f;d.c=b;d.p="";return d(0)}([function(f,d,b){function a(a,b){"object"===("undefined"===typeof a?"undefined":c(a))&&(b=
a,a=void 0);b=b||{};a=h(a);var d=a.source,e=a.id,g=a.path;g=p[e]&&g in p[e].nsps;b.forceNew||b["force new connection"]||!1===b.multiplex||g?(m("ignoring socket cache for %s",d),d=n(d,b)):(p[e]||(m("new io instance for %s",d),p[e]=n(d,b)),d=p[e]);a.query&&!b.query&&(b.query=a.query);return d.socket(a.path,b)}var c="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?
"symbol":typeof a},h=b(1),k=b(7),n=b(12),m=b(3)("socket.io-client");f.exports=d=a;var p=d.managers={};d.protocol=k.protocol;d.connect=a;d.Manager=b(12);d.Socket=b(37)},function(f,d,b){(function(a){var c=b(2),h=b(3)("socket.io-client:url");f.exports=function(b,d){var k=b;d=d||a.location;null==b&&(b=d.protocol+"//"+d.host);"string"===typeof b&&("/"===b.charAt(0)&&(b="/"===b.charAt(1)?d.protocol+b:d.host+b),/^(https?|wss?):\/\//.test(b)||(h("protocol-less url %s",b),b="undefined"!==typeof d?d.protocol+
"//"+b:"https://"+b),h("parse %s",b),k=c(b));k.port||(/^(http|ws)$/.test(k.protocol)?k.port="80":/^(http|ws)s$/.test(k.protocol)&&(k.port="443"));k.path=k.path||"/";b=-1!==k.host.indexOf(":")?"["+k.host+"]":k.host;k.id=k.protocol+"://"+b+":"+k.port;k.href=k.protocol+"://"+b+(d&&d.port===k.port?"":":"+k.port);return k}}).call(d,function(){return this}())},function(f,d){var b=/^(?:(?![^:@]+:[^:@\/]*@)(http|https|ws|wss):\/\/)?((?:(([^:@]*)(?::([^:@]*))?)?@)?((?:[a-f0-9]{0,4}:){2,7}[a-f0-9]{0,4}|[^:\/?#]*)(?::(\d*))?)(((\/(?:[^?#](?![^?#\/]*\.[^?#\/.]+(?:[?#]|$)))*\/?)?([^?#\/]*))(?:\?([^#]*))?(?:#(.*))?)/,
a="source protocol authority userInfo user password host port relative path directory file query anchor".split(" ");f.exports=function(d){var h=d,c=d.indexOf("["),n=d.indexOf("]");-1!=c&&-1!=n&&(d=d.substring(0,c)+d.substring(c,n).replace(/:/g,";")+d.substring(n,d.length));d=b.exec(d||"");for(var f={},p=14;p--;)f[a[p]]=d[p]||"";-1!=c&&-1!=n&&(f.source=h,f.host=f.host.substring(1,f.host.length-1).replace(/;/g,":"),f.authority=f.authority.replace("[","").replace("]","").replace(/;/g,":"),f.ipv6uri=
!0);return f}},function(f,d,b){(function(a){function c(){try{var b=d.storage.debug}catch(m){}!b&&"undefined"!==typeof a&&"env"in a&&(b=a.env.DEBUG);return b}d=f.exports=b(5);d.log=function(){return"object"===typeof console&&console.log&&Function.prototype.apply.call(console.log,console,arguments)};d.formatArgs=function(a){var b=this.useColors;a[0]=(b?"%c":"")+this.namespace+(b?" %c":" ")+a[0]+(b?"%c ":" ")+"+"+d.humanize(this.diff);if(b){b="color: "+this.color;a.splice(1,0,b,"color: inherit");var h=
0,c=0;a[0].replace(/%[a-zA-Z%]/g,function(a){"%%"!==a&&(h++,"%c"===a&&(c=h))});a.splice(c,0,b)}};d.save=function(a){try{null==a?d.storage.removeItem("debug"):d.storage.debug=a}catch(m){}};d.load=c;d.useColors=function(){return"undefined"!==typeof window&&window.process&&"renderer"===window.process.type?!0:"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/(edge|trident)\/(\d+)/)?!1:"undefined"!==typeof document&&document.documentElement&&document.documentElement.style&&
document.documentElement.style.WebkitAppearance||"undefined"!==typeof window&&window.console&&(window.console.firebug||window.console.exception&&window.console.table)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/firefox\/(\d+)/)&&31<=parseInt(RegExp.$1,10)||"undefined"!==typeof navigator&&navigator.userAgent&&navigator.userAgent.toLowerCase().match(/applewebkit\/(\d+)/)};var h=d;if("undefined"!=typeof chrome&&"undefined"!=typeof chrome.storage)var k=
chrome.storage.local;else a:{try{k=window.localStorage;break a}catch(n){}k=void 0}h.storage=k;d.colors="#0000CC #0000FF #0033CC #0033FF #0066CC #0066FF #0099CC #0099FF #00CC00 #00CC33 #00CC66 #00CC99 #00CCCC #00CCFF #3300CC #3300FF #3333CC #3333FF #3366CC #3366FF #3399CC #3399FF #33CC00 #33CC33 #33CC66 #33CC99 #33CCCC #33CCFF #6600CC #6600FF #6633CC #6633FF #66CC00 #66CC33 #9900CC #9900FF #9933CC #9933FF #99CC00 #99CC33 #CC0000 #CC0033 #CC0066 #CC0099 #CC00CC #CC00FF #CC3300 #CC3333 #CC3366 #CC3399 #CC33CC #CC33FF #CC6600 #CC6633 #CC9900 #CC9933 #CCCC00 #CCCC33 #FF0000 #FF0033 #FF0066 #FF0099 #FF00CC #FF00FF #FF3300 #FF3333 #FF3366 #FF3399 #FF33CC #FF33FF #FF6600 #FF6633 #FF9900 #FF9933 #FFCC00 #FFCC33".split(" ");
d.formatters.j=function(a){try{return JSON.stringify(a)}catch(m){return"[UnexpectedJSONParseError]: "+m.message}};d.enable(c())}).call(d,b(4))},function(f,d){function b(){throw Error("setTimeout has not been defined");}function a(){throw Error("clearTimeout has not been defined");}function c(e){if(l===setTimeout)return setTimeout(e,0);if((l===b||!l)&&setTimeout)return l=setTimeout,setTimeout(e,0);try{return l(e,0)}catch(t){try{return l.call(null,e,0)}catch(v){return l.call(this,e,0)}}}function h(e){if(q===
clearTimeout)return clearTimeout(e);if((q===a||!q)&&clearTimeout)return q=clearTimeout,clearTimeout(e);try{return q(e)}catch(t){try{return q.call(null,e)}catch(v){return q.call(this,e)}}}function k(){e&&g&&(e=!1,g.length?r=g.concat(r):w=-1,r.length&&n())}function n(){if(!e){var a=c(k);e=!0;for(var b=r.length;b;){g=r;for(r=[];++w<b;)g&&g[w].run();w=-1;b=r.length}g=null;e=!1;h(a)}}function m(e,g){this.fun=e;this.array=g}function p(){}f=f.exports={};try{var l="function"===typeof setTimeout?setTimeout:
b}catch(x){l=b}try{var q="function"===typeof clearTimeout?clearTimeout:a}catch(x){q=a}var r=[],e=!1,g,w=-1;f.nextTick=function(g){var a=Array(arguments.length-1);if(1<arguments.length)for(var b=1;b<arguments.length;b++)a[b-1]=arguments[b];r.push(new m(g,a));1!==r.length||e||c(n)};m.prototype.run=function(){this.fun.apply(null,this.array)};f.title="browser";f.browser=!0;f.env={};f.argv=[];f.version="";f.versions={};f.on=p;f.addListener=p;f.once=p;f.off=p;f.removeListener=p;f.removeAllListeners=p;f.emit=
p;f.prependListener=p;f.prependOnceListener=p;f.listeners=function(e){return[]};f.binding=function(e){throw Error("process.binding is not supported");};f.cwd=function(){return"/"};f.chdir=function(e){throw Error("process.chdir is not supported");};f.umask=function(){return 0}},function(f,d,b){function a(a){var b=0,h;for(h in a)b=(b<<5)-b+a.charCodeAt(h),b|=0;return d.colors[Math.abs(b)%d.colors.length]}function c(b){function c(){if(c.enabled){var a=+new Date;c.diff=a-(k||a);c.prev=k;k=c.curr=a;var b=
Array(arguments.length);for(a=0;a<b.length;a++)b[a]=arguments[a];b[0]=d.coerce(b[0]);"string"!==typeof b[0]&&b.unshift("%O");var h=0;b[0]=b[0].replace(/%([a-zA-Z%])/g,function(a,e){if("%%"===a)return a;h++;e=d.formatters[e];"function"===typeof e&&(a=e.call(c,b[h]),b.splice(h,1),h--);return a});d.formatArgs.call(c,b);(c.log||d.log||console.log.bind(console)).apply(c,b)}}var k;c.namespace=b;c.enabled=d.enabled(b);c.useColors=d.useColors();c.color=a(b);c.destroy=h;"function"===typeof d.init&&d.init(c);
d.instances.push(c);return c}function h(){var a=d.instances.indexOf(this);return-1!==a?(d.instances.splice(a,1),!0):!1}d=f.exports=c.debug=c["default"]=c;d.coerce=function(a){return a instanceof Error?a.stack||a.message:a};d.disable=function(){d.enable("")};d.enable=function(a){d.save(a);d.names=[];d.skips=[];var b,c=("string"===typeof a?a:"").split(/[\s,]+/),h=c.length;for(b=0;b<h;b++)c[b]&&(a=c[b].replace(/\*/g,".*?"),"-"===a[0]?d.skips.push(new RegExp("^"+a.substr(1)+"$")):d.names.push(new RegExp("^"+
a+"$")));for(b=0;b<d.instances.length;b++)a=d.instances[b],a.enabled=d.enabled(a.namespace)};d.enabled=function(a){if("*"===a[a.length-1])return!0;var b;var c=0;for(b=d.skips.length;c<b;c++)if(d.skips[c].test(a))return!1;c=0;for(b=d.names.length;c<b;c++)if(d.names[c].test(a))return!0;return!1};d.humanize=b(6);d.instances=[];d.names=[];d.skips=[];d.formatters={}},function(f,d){function b(a){a=String(a);if(!(100<a.length)&&(a=/^((?:\d+)?\.?\d+) *(milliseconds?|msecs?|ms|seconds?|secs?|s|minutes?|mins?|m|hours?|hrs?|h|days?|d|years?|yrs?|y)?$/i.exec(a))){var b=
parseFloat(a[1]);switch((a[2]||"ms").toLowerCase()){case "years":case "year":case "yrs":case "yr":case "y":return b*c;case "days":case "day":case "d":return 864E5*b;case "hours":case "hour":case "hrs":case "hr":case "h":return 36E5*b;case "minutes":case "minute":case "mins":case "min":case "m":return 6E4*b;case "seconds":case "second":case "secs":case "sec":case "s":return 1E3*b;case "milliseconds":case "millisecond":case "msecs":case "msec":case "ms":return b}}}function a(a,b,c){if(!(a<b))return a<
1.5*b?Math.floor(a/b)+" "+c:Math.ceil(a/b)+" "+c+"s"}var c=315576E5;f.exports=function(c,d){d=d||{};var h=typeof c;if("string"===h&&0<c.length)return b(c);if("number"===h&&!1===isNaN(c))return d.long?a(c,864E5,"day")||a(c,36E5,"hour")||a(c,6E4,"minute")||a(c,1E3,"second")||c+" ms":864E5<=c?Math.round(c/864E5)+"d":36E5<=c?Math.round(c/36E5)+"h":6E4<=c?Math.round(c/6E4)+"m":1E3<=c?Math.round(c/1E3)+"s":c+"ms";throw Error("val is not a non-empty string or a valid number. val="+JSON.stringify(c));}},
function(f,d,b){function a(){}function c(a){var e=""+a.type;if(d.BINARY_EVENT===a.type||d.BINARY_ACK===a.type)e+=a.attachments+"-";a.nsp&&"/"!==a.nsp&&(e+=a.nsp+",");null!=a.id&&(e+=a.id);if(null!=a.data){try{var b=JSON.stringify(a.data)}catch(x){b=!1}if(!1!==b)e+=b;else return r}m("encoded %j as %s",a,e);return e}function h(a,g){p.removeBlobs(a,function(a){var e=p.deconstructPacket(a);a=c(e.packet);e=e.buffers;e.unshift(a);g(e)})}function k(){this.reconstructor=null}function n(a){this.reconPack=
a;this.buffers=[]}var m=b(3)("socket.io-parser");f=b(8);var p=b(9),l=b(10),q=b(11);d.protocol=4;d.types="CONNECT DISCONNECT EVENT ACK ERROR BINARY_EVENT BINARY_ACK".split(" ");d.CONNECT=0;d.DISCONNECT=1;d.EVENT=2;d.ACK=3;d.ERROR=4;d.BINARY_EVENT=5;d.BINARY_ACK=6;d.Encoder=a;d.Decoder=k;var r=d.ERROR+'"encode error"';a.prototype.encode=function(a,g){m("encoding packet %j",a);d.BINARY_EVENT===a.type||d.BINARY_ACK===a.type?h(a,g):(a=c(a),g([a]))};f(k.prototype);k.prototype.add=function(a){if("string"===
typeof a){a:{var g=0,e={type:Number(a.charAt(0))};if(null==d.types[e.type])a={type:d.ERROR,data:"parser error: unknown packet type "+e.type};else{if(d.BINARY_EVENT===e.type||d.BINARY_ACK===e.type){for(var b="";"-"!==a.charAt(++g)&&(b+=a.charAt(g),g!=a.length););if(b!=Number(b)||"-"!==a.charAt(g))throw Error("Illegal attachments");e.attachments=Number(b)}if("/"===a.charAt(g+1))for(e.nsp="";++g;){b=a.charAt(g);if(","===b)break;e.nsp+=b;if(g===a.length)break}else e.nsp="/";b=a.charAt(g+1);if(""!==b&&
Number(b)==b){for(e.id="";++g;){b=a.charAt(g);if(null==b||Number(b)!=b){--g;break}e.id+=a.charAt(g);if(g===a.length)break}e.id=Number(e.id)}if(a.charAt(++g)){g=a.substr(g);try{var c=JSON.parse(g)}catch(v){c=!1}if(!1===c||e.type!==d.ERROR&&!l(c)){a={type:d.ERROR,data:"parser error: invalid payload"};break a}else e.data=c}m("decoded %s as %j",a,e);a=e}}d.BINARY_EVENT===a.type||d.BINARY_ACK===a.type?(this.reconstructor=new n(a),0===this.reconstructor.reconPack.attachments&&this.emit("decoded",a)):this.emit("decoded",
a)}else if(q(a)||a.base64)if(this.reconstructor){if(a=this.reconstructor.takeBinaryData(a))this.reconstructor=null,this.emit("decoded",a)}else throw Error("got binary data when not reconstructing a packet");else throw Error("Unknown type: "+a);};k.prototype.destroy=function(){this.reconstructor&&this.reconstructor.finishedReconstruction()};n.prototype.takeBinaryData=function(a){this.buffers.push(a);return this.buffers.length===this.reconPack.attachments?(a=p.reconstructPacket(this.reconPack,this.buffers),
this.finishedReconstruction(),a):null};n.prototype.finishedReconstruction=function(){this.reconPack=null;this.buffers=[]}},function(f,d,b){function a(b){if(b){for(var c in a.prototype)b[c]=a.prototype[c];return b}}f.exports=a;a.prototype.on=a.prototype.addEventListener=function(a,b){this._callbacks=this._callbacks||{};(this._callbacks["$"+a]=this._callbacks["$"+a]||[]).push(b);return this};a.prototype.once=function(a,b){function c(){this.off(a,c);b.apply(this,arguments)}c.fn=b;this.on(a,c);return this};
a.prototype.off=a.prototype.removeListener=a.prototype.removeAllListeners=a.prototype.removeEventListener=function(a,b){this._callbacks=this._callbacks||{};if(0==arguments.length)return this._callbacks={},this;var c=this._callbacks["$"+a];if(!c)return this;if(1==arguments.length)return delete this._callbacks["$"+a],this;for(var d,h=0;h<c.length;h++)if(d=c[h],d===b||d.fn===b){c.splice(h,1);break}return this};a.prototype.emit=function(a){this._callbacks=this._callbacks||{};var b=[].slice.call(arguments,
1),c=this._callbacks["$"+a];if(c){c=c.slice(0);for(var d=0,f=c.length;d<f;++d)c[d].apply(this,b)}return this};a.prototype.listeners=function(a){this._callbacks=this._callbacks||{};return this._callbacks["$"+a]||[]};a.prototype.hasListeners=function(a){return!!this.listeners(a).length}},function(f,d,b){(function(a){function c(a,b){if(!a)return a;if(n(a)){var e={_placeholder:!0,num:b.length};b.push(a);return e}if(f(a)){e=Array(a.length);for(var g=0;g<a.length;g++)e[g]=c(a[g],b);return e}if("object"===
typeof a&&!(a instanceof Date)){e={};for(g in a)e[g]=c(a[g],b);return e}return a}function h(a,b){if(!a)return a;if(a&&a._placeholder)return b[a.num];if(f(a))for(var e=0;e<a.length;e++)a[e]=h(a[e],b);else if("object"===typeof a)for(e in a)a[e]=h(a[e],b);return a}var f=b(10),n=b(11),m=Object.prototype.toString,p="function"===typeof a.Blob||"[object BlobConstructor]"===m.call(a.Blob),l="function"===typeof a.File||"[object FileConstructor]"===m.call(a.File);d.deconstructPacket=function(a){var b=[];a.data=
c(a.data,b);a.attachments=b.length;return{packet:a,buffers:b}};d.reconstructPacket=function(a,b){a.data=h(a.data,b);a.attachments=void 0;return a};d.removeBlobs=function(a,b){function e(a,d,h){if(!a)return a;if(p&&a instanceof Blob||l&&a instanceof File){g++;var u=new FileReader;u.onload=function(){h?h[d]=this.result:c=this.result;--g||b(c)};u.readAsArrayBuffer(a)}else if(f(a))for(u=0;u<a.length;u++)e(a[u],u,a);else if("object"===typeof a&&!n(a))for(u in a)e(a[u],u,a)}var g=0,c=a;e(c);g||b(c)}}).call(d,
function(){return this}())},function(f,d){var b={}.toString;f.exports=Array.isArray||function(a){return"[object Array]"==b.call(a)}},function(f,d){(function(b){f.exports=function(h){return a&&b.Buffer.isBuffer(h)||c&&(h instanceof b.ArrayBuffer||d(h))};var a="function"===typeof b.Buffer&&"function"===typeof b.Buffer.isBuffer,c="function"===typeof b.ArrayBuffer,d=function(){return c&&"function"===typeof b.ArrayBuffer.isView?b.ArrayBuffer.isView:function(a){return a.buffer instanceof b.ArrayBuffer}}()}).call(d,
function(){return this}())},function(f,d,b){function a(b,e){if(!(this instanceof a))return new a(b,e);b&&"object"===("undefined"===typeof b?"undefined":c(b))&&(e=b,b=void 0);e=e||{};e.path=e.path||"/socket.io";this.nsps={};this.subs=[];this.opts=e;this.reconnection(!1!==e.reconnection);this.reconnectionAttempts(e.reconnectionAttempts||Infinity);this.reconnectionDelay(e.reconnectionDelay||1E3);this.reconnectionDelayMax(e.reconnectionDelayMax||5E3);this.randomizationFactor(e.randomizationFactor||.5);
this.backoff=new r({min:this.reconnectionDelay(),max:this.reconnectionDelayMax(),jitter:this.randomizationFactor()});this.timeout(null==e.timeout?2E4:e.timeout);this.readyState="closed";this.uri=b;this.connecting=[];this.lastPing=null;this.encoding=!1;this.packetBuffer=[];var g=e.parser||n;this.encoder=new g.Encoder;this.decoder=new g.Decoder;(this.autoConnect=!1!==e.autoConnect)&&this.open()}var c="function"===typeof Symbol&&"symbol"===typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&
"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},h=b(13),k=b(37);d=b(8);var n=b(7),m=b(39),p=b(40),l=b(3)("socket.io-client:manager"),q=b(36),r=b(41),e=Object.prototype.hasOwnProperty;f.exports=a;a.prototype.emitAll=function(){this.emit.apply(this,arguments);for(var a in this.nsps)e.call(this.nsps,a)&&this.nsps[a].emit.apply(this.nsps[a],arguments)};a.prototype.updateSocketIds=function(){for(var a in this.nsps)e.call(this.nsps,a)&&(this.nsps[a].id=this.generateId(a))};
a.prototype.generateId=function(a){return("/"===a?"":a+"#")+this.engine.id};d(a.prototype);a.prototype.reconnection=function(a){if(!arguments.length)return this._reconnection;this._reconnection=!!a;return this};a.prototype.reconnectionAttempts=function(a){if(!arguments.length)return this._reconnectionAttempts;this._reconnectionAttempts=a;return this};a.prototype.reconnectionDelay=function(a){if(!arguments.length)return this._reconnectionDelay;this._reconnectionDelay=a;this.backoff&&this.backoff.setMin(a);
return this};a.prototype.randomizationFactor=function(a){if(!arguments.length)return this._randomizationFactor;this._randomizationFactor=a;this.backoff&&this.backoff.setJitter(a);return this};a.prototype.reconnectionDelayMax=function(a){if(!arguments.length)return this._reconnectionDelayMax;this._reconnectionDelayMax=a;this.backoff&&this.backoff.setMax(a);return this};a.prototype.timeout=function(a){if(!arguments.length)return this._timeout;this._timeout=a;return this};a.prototype.maybeReconnectOnOpen=
function(){!this.reconnecting&&this._reconnection&&0===this.backoff.attempts&&this.reconnect()};a.prototype.open=a.prototype.connect=function(a,b){l("readyState %s",this.readyState);if(~this.readyState.indexOf("open"))return this;l("opening %s",this.uri);var e=this.engine=h(this.uri,this.opts),g=this;this.readyState="opening";this.skipReconnect=!1;var c=m(e,"open",function(){g.onopen();a&&a()});b=m(e,"error",function(b){l("connect_error");g.cleanup();g.readyState="closed";g.emitAll("connect_error",
b);if(a){var e=Error("Connection error");e.data=b;a(e)}else g.maybeReconnectOnOpen()});if(!1!==this._timeout){var d=this._timeout;l("connect attempt will timeout after %d",d);var f=setTimeout(function(){l("connect attempt timed out after %d",d);c.destroy();e.close();e.emit("error","timeout");g.emitAll("connect_timeout",d)},d);this.subs.push({destroy:function(){clearTimeout(f)}})}this.subs.push(c);this.subs.push(b);return this};a.prototype.onopen=function(){l("open");this.cleanup();this.readyState=
"open";this.emit("open");var a=this.engine;this.subs.push(m(a,"data",p(this,"ondata")));this.subs.push(m(a,"ping",p(this,"onping")));this.subs.push(m(a,"pong",p(this,"onpong")));this.subs.push(m(a,"error",p(this,"onerror")));this.subs.push(m(a,"close",p(this,"onclose")));this.subs.push(m(this.decoder,"decoded",p(this,"ondecoded")))};a.prototype.onping=function(){this.lastPing=new Date;this.emitAll("ping")};a.prototype.onpong=function(){this.emitAll("pong",new Date-this.lastPing)};a.prototype.ondata=
function(a){this.decoder.add(a)};a.prototype.ondecoded=function(a){this.emit("packet",a)};a.prototype.onerror=function(a){l("error",a);this.emitAll("error",a)};a.prototype.socket=function(a,b){function e(){~q(c.connecting,g)||c.connecting.push(g)}var g=this.nsps[a];if(!g){g=new k(this,a,b);this.nsps[a]=g;var c=this;g.on("connecting",e);g.on("connect",function(){g.id=c.generateId(a)});this.autoConnect&&e()}return g};a.prototype.destroy=function(a){a=q(this.connecting,a);~a&&this.connecting.splice(a,
1);this.connecting.length||this.close()};a.prototype.packet=function(a){l("writing packet %j",a);var b=this;a.query&&0===a.type&&(a.nsp+="?"+a.query);b.encoding?b.packetBuffer.push(a):(b.encoding=!0,this.encoder.encode(a,function(e){for(var c=0;c<e.length;c++)b.engine.write(e[c],a.options);b.encoding=!1;b.processPacketQueue()}))};a.prototype.processPacketQueue=function(){if(0<this.packetBuffer.length&&!this.encoding){var a=this.packetBuffer.shift();this.packet(a)}};a.prototype.cleanup=function(){l("cleanup");
for(var a=this.subs.length,b=0;b<a;b++)this.subs.shift().destroy();this.packetBuffer=[];this.encoding=!1;this.lastPing=null;this.decoder.destroy()};a.prototype.close=a.prototype.disconnect=function(){l("disconnect");this.skipReconnect=!0;this.reconnecting=!1;"opening"===this.readyState&&this.cleanup();this.backoff.reset();this.readyState="closed";this.engine&&this.engine.close()};a.prototype.onclose=function(a){l("onclose");this.cleanup();this.backoff.reset();this.readyState="closed";this.emit("close",
a);this._reconnection&&!this.skipReconnect&&this.reconnect()};a.prototype.reconnect=function(){if(this.reconnecting||this.skipReconnect)return this;var a=this;if(this.backoff.attempts>=this._reconnectionAttempts)l("reconnect failed"),this.backoff.reset(),this.emitAll("reconnect_failed"),this.reconnecting=!1;else{var b=this.backoff.duration();l("will wait %dms before reconnect attempt",b);this.reconnecting=!0;var e=setTimeout(function(){a.skipReconnect||(l("attempting reconnect"),a.emitAll("reconnect_attempt",
a.backoff.attempts),a.emitAll("reconnecting",a.backoff.attempts),a.skipReconnect||a.open(function(b){b?(l("reconnect attempt error"),a.reconnecting=!1,a.reconnect(),a.emitAll("reconnect_error",b.data)):(l("reconnect success"),a.onreconnect())}))},b);this.subs.push({destroy:function(){clearTimeout(e)}})}};a.prototype.onreconnect=function(){var a=this.backoff.attempts;this.reconnecting=!1;this.backoff.reset();this.updateSocketIds();this.emitAll("reconnect",a)}},function(f,d,b){f.exports=b(14);f.exports.parser=
b(21)},function(f,d,b){(function(a){function c(b,e){if(!(this instanceof c))return new c(b,e);e=e||{};b&&"object"===typeof b&&(e=b,b=null);b?(b=l(b),e.hostname=b.host,e.secure="https"===b.protocol||"wss"===b.protocol,e.port=b.port,b.query&&(e.query=b.query)):e.host&&(e.hostname=l(e.host).host);this.secure=null!=e.secure?e.secure:a.location&&"https:"===location.protocol;e.hostname&&!e.port&&(e.port=this.secure?"443":"80");this.agent=e.agent||!1;this.hostname=e.hostname||(a.location?location.hostname:
"localhost");this.port=e.port||(a.location&&location.port?location.port:this.secure?443:80);this.query=e.query||{};"string"===typeof this.query&&(this.query=q.decode(this.query));this.upgrade=!1!==e.upgrade;this.path=(e.path||"/engine.io").replace(/\/$/,"")+"/";this.forceJSONP=!!e.forceJSONP;this.jsonp=!1!==e.jsonp;this.forceBase64=!!e.forceBase64;this.enablesXDR=!!e.enablesXDR;this.timestampParam=e.timestampParam||"t";this.timestampRequests=e.timestampRequests;this.transports=e.transports||["polling",
"websocket"];this.transportOptions=e.transportOptions||{};this.readyState="";this.writeBuffer=[];this.prevBufferLen=0;this.policyPort=e.policyPort||843;this.rememberUpgrade=e.rememberUpgrade||!1;this.binaryType=null;this.onlyBinaryUpgrades=e.onlyBinaryUpgrades;this.perMessageDeflate=!1!==e.perMessageDeflate?e.perMessageDeflate||{}:!1;!0===this.perMessageDeflate&&(this.perMessageDeflate={});this.perMessageDeflate&&null==this.perMessageDeflate.threshold&&(this.perMessageDeflate.threshold=1024);this.pfx=
e.pfx||null;this.key=e.key||null;this.passphrase=e.passphrase||null;this.cert=e.cert||null;this.ca=e.ca||null;this.ciphers=e.ciphers||null;this.rejectUnauthorized=void 0===e.rejectUnauthorized?!0:e.rejectUnauthorized;this.forceNode=!!e.forceNode;b="object"===typeof a&&a;b.global===b&&(e.extraHeaders&&0<Object.keys(e.extraHeaders).length&&(this.extraHeaders=e.extraHeaders),e.localAddress&&(this.localAddress=e.localAddress));this.pingTimeoutTimer=this.pingIntervalTimer=this.pingTimeout=this.pingInterval=
this.upgrades=this.id=null;this.open()}var d=b(15),k=b(8),n=b(3)("engine.io-client:socket"),m=b(36),p=b(21),l=b(2),q=b(30);f.exports=c;c.priorWebsocketSuccess=!1;k(c.prototype);c.protocol=p.protocol;c.Socket=c;c.Transport=b(20);c.transports=b(15);c.parser=b(21);c.prototype.createTransport=function(a){n('creating transport "%s"',a);var b=this.query,c={},h;for(h in b)b.hasOwnProperty(h)&&(c[h]=b[h]);c.EIO=p.protocol;c.transport=a;b=this.transportOptions[a]||{};this.id&&(c.sid=this.id);return new d[a]({query:c,
socket:this,agent:b.agent||this.agent,hostname:b.hostname||this.hostname,port:b.port||this.port,secure:b.secure||this.secure,path:b.path||this.path,forceJSONP:b.forceJSONP||this.forceJSONP,jsonp:b.jsonp||this.jsonp,forceBase64:b.forceBase64||this.forceBase64,enablesXDR:b.enablesXDR||this.enablesXDR,timestampRequests:b.timestampRequests||this.timestampRequests,timestampParam:b.timestampParam||this.timestampParam,policyPort:b.policyPort||this.policyPort,pfx:b.pfx||this.pfx,key:b.key||this.key,passphrase:b.passphrase||
this.passphrase,cert:b.cert||this.cert,ca:b.ca||this.ca,ciphers:b.ciphers||this.ciphers,rejectUnauthorized:b.rejectUnauthorized||this.rejectUnauthorized,perMessageDeflate:b.perMessageDeflate||this.perMessageDeflate,extraHeaders:b.extraHeaders||this.extraHeaders,forceNode:b.forceNode||this.forceNode,localAddress:b.localAddress||this.localAddress,requestTimeout:b.requestTimeout||this.requestTimeout,protocols:b.protocols||void 0})};c.prototype.open=function(){if(this.rememberUpgrade&&c.priorWebsocketSuccess&&
-1!==this.transports.indexOf("websocket"))var a="websocket";else{if(0===this.transports.length){var b=this;setTimeout(function(){b.emit("error","No transports available")},0);return}a=this.transports[0]}this.readyState="opening";try{a=this.createTransport(a)}catch(g){this.transports.shift();this.open();return}a.open();this.setTransport(a)};c.prototype.setTransport=function(a){n("setting transport %s",a.name);var b=this;this.transport&&(n("clearing existing transport %s",this.transport.name),this.transport.removeAllListeners());
this.transport=a;a.on("drain",function(){b.onDrain()}).on("packet",function(a){b.onPacket(a)}).on("error",function(a){b.onError(a)}).on("close",function(){b.onClose("transport close")})};c.prototype.probe=function(a){function b(){if(m.onlyBinaryUpgrades){var b=!this.supportsBinary&&m.transport.supportsBinary;p=p||b}p||(n('probe transport "%s" opened',a),l.send([{type:"ping",data:"probe"}]),l.once("packet",function(b){p||("pong"===b.type&&"probe"===b.data?(n('probe transport "%s" pong',a),m.upgrading=
!0,m.emit("upgrading",l),l&&(c.priorWebsocketSuccess="websocket"===l.name,n('pausing current transport "%s"',m.transport.name),m.transport.pause(function(){p||"closed"===m.readyState||(n("changing transport and sending upgrade packet"),u(),m.setTransport(l),l.send([{type:"upgrade"}]),m.emit("upgrade",l),l=null,m.upgrading=!1,m.flush())}))):(n('probe transport "%s" failed',a),b=Error("probe error"),b.transport=l.name,m.emit("upgradeError",b)))}))}function d(){p||(p=!0,u(),l.close(),l=null)}function h(b){var e=
Error("probe error: "+b);e.transport=l.name;d();n('probe transport "%s" failed because of error: %s',a,b);m.emit("upgradeError",e)}function f(){h("transport closed")}function r(){h("socket closed")}function k(a){l&&a.name!==l.name&&(n('"%s" works - aborting "%s"',a.name,l.name),d())}function u(){l.removeListener("open",b);l.removeListener("error",h);l.removeListener("close",f);m.removeListener("close",r);m.removeListener("upgrading",k)}n('probing transport "%s"',a);var l=this.createTransport(a,{probe:1}),
p=!1,m=this;c.priorWebsocketSuccess=!1;l.once("open",b);l.once("error",h);l.once("close",f);this.once("close",r);this.once("upgrading",k);l.open()};c.prototype.onOpen=function(){n("socket open");this.readyState="open";c.priorWebsocketSuccess="websocket"===this.transport.name;this.emit("open");this.flush();if("open"===this.readyState&&this.upgrade&&this.transport.pause){n("starting upgrade probes");for(var a=0,b=this.upgrades.length;a<b;a++)this.probe(this.upgrades[a])}};c.prototype.onPacket=function(a){if("opening"===
this.readyState||"open"===this.readyState||"closing"===this.readyState)switch(n('socket receive: type "%s", data "%s"',a.type,a.data),this.emit("packet",a),this.emit("heartbeat"),a.type){case "open":this.onHandshake(JSON.parse(a.data));break;case "pong":this.setPing();this.emit("pong");break;case "error":var b=Error("server error");b.code=a.data;this.onError(b);break;case "message":this.emit("data",a.data),this.emit("message",a.data)}else n('packet received with socket readyState "%s"',this.readyState)};
c.prototype.onHandshake=function(a){this.emit("handshake",a);this.id=a.sid;this.transport.query.sid=a.sid;this.upgrades=this.filterUpgrades(a.upgrades);this.pingInterval=a.pingInterval;this.pingTimeout=a.pingTimeout;this.onOpen();"closed"!==this.readyState&&(this.setPing(),this.removeListener("heartbeat",this.onHeartbeat),this.on("heartbeat",this.onHeartbeat))};c.prototype.onHeartbeat=function(a){clearTimeout(this.pingTimeoutTimer);var b=this;b.pingTimeoutTimer=setTimeout(function(){if("closed"!==
b.readyState)b.onClose("ping timeout")},a||b.pingInterval+b.pingTimeout)};c.prototype.setPing=function(){var a=this;clearTimeout(a.pingIntervalTimer);a.pingIntervalTimer=setTimeout(function(){n("writing ping packet - expecting pong within %sms",a.pingTimeout);a.ping();a.onHeartbeat(a.pingTimeout)},a.pingInterval)};c.prototype.ping=function(){var a=this;this.sendPacket("ping",function(){a.emit("ping")})};c.prototype.onDrain=function(){this.writeBuffer.splice(0,this.prevBufferLen);this.prevBufferLen=
0;0===this.writeBuffer.length?this.emit("drain"):this.flush()};c.prototype.flush=function(){"closed"!==this.readyState&&this.transport.writable&&!this.upgrading&&this.writeBuffer.length&&(n("flushing %d packets in socket",this.writeBuffer.length),this.transport.send(this.writeBuffer),this.prevBufferLen=this.writeBuffer.length,this.emit("flush"))};c.prototype.write=c.prototype.send=function(a,b,c){this.sendPacket("message",a,b,c);return this};c.prototype.sendPacket=function(a,b,c,d){"function"===typeof b&&
(d=b,b=void 0);"function"===typeof c&&(d=c,c=null);if("closing"!==this.readyState&&"closed"!==this.readyState){c=c||{};c.compress=!1!==c.compress;a={type:a,data:b,options:c};this.emit("packetCreate",a);this.writeBuffer.push(a);if(d)this.once("flush",d);this.flush()}};c.prototype.close=function(){function a(){d.onClose("forced close");n("socket closing - telling transport to close");d.transport.close()}function b(){d.removeListener("upgrade",b);d.removeListener("upgradeError",b);a()}function c(){d.once("upgrade",
b);d.once("upgradeError",b)}if("opening"===this.readyState||"open"===this.readyState){this.readyState="closing";var d=this;if(this.writeBuffer.length)this.once("drain",function(){this.upgrading?c():a()});else this.upgrading?c():a()}return this};c.prototype.onError=function(a){n("socket error %j",a);c.priorWebsocketSuccess=!1;this.emit("error",a);this.onClose("transport error",a)};c.prototype.onClose=function(a,b){if("opening"===this.readyState||"open"===this.readyState||"closing"===this.readyState)n('socket close with reason: "%s"',
a),clearTimeout(this.pingIntervalTimer),clearTimeout(this.pingTimeoutTimer),this.transport.removeAllListeners("close"),this.transport.close(),this.transport.removeAllListeners(),this.readyState="closed",this.id=null,this.emit("close",a,b),this.writeBuffer=[],this.prevBufferLen=0};c.prototype.filterUpgrades=function(a){for(var b=[],c=0,d=a.length;c<d;c++)~m(this.transports,a[c])&&b.push(a[c]);return b}}).call(d,function(){return this}())},function(f,d,b){(function(a){var c=b(16),h=b(18),f=b(33),n=
b(34);d.polling=function(b){var d=!1,l=!1,k=!1!==b.jsonp;a.location&&(l="https:"===location.protocol,(d=location.port)||(d=l?443:80),d=b.hostname!==location.hostname||d!==b.port,l=b.secure!==l);b.xdomain=d;b.xscheme=l;if("open"in new c(b)&&!b.forceJSONP)return new h(b);if(!k)throw Error("JSONP disabled");return new f(b)};d.websocket=n}).call(d,function(){return this}())},function(f,d,b){(function(a){var c=b(17);f.exports=function(b){var d=b.xdomain,h=b.xscheme;b=b.enablesXDR;try{if("undefined"!==
typeof XMLHttpRequest&&(!d||c))return new XMLHttpRequest}catch(m){}try{if("undefined"!==typeof XDomainRequest&&!h&&b)return new XDomainRequest}catch(m){}if(!d)try{return new (a[["Active"].concat("Object").join("X")])("Microsoft.XMLHTTP")}catch(m){}}}).call(d,function(){return this}())},function(f,d){try{f.exports="undefined"!==typeof XMLHttpRequest&&"withCredentials"in new XMLHttpRequest}catch(b){f.exports=!1}},function(f,d,b){(function(a){function c(){}function d(b){p.call(this,b);this.requestTimeout=
b.requestTimeout;this.extraHeaders=b.extraHeaders;if(a.location){var c="https:"===location.protocol,e=location.port;e||(e=c?443:80);this.xd=b.hostname!==a.location.hostname||e!==b.port;this.xs=b.secure!==c}}function k(a){this.method=a.method||"GET";this.uri=a.uri;this.xd=!!a.xd;this.xs=!!a.xs;this.async=!1!==a.async;this.data=void 0!==a.data?a.data:null;this.agent=a.agent;this.isBinary=a.isBinary;this.supportsBinary=a.supportsBinary;this.enablesXDR=a.enablesXDR;this.requestTimeout=a.requestTimeout;
this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.extraHeaders=a.extraHeaders;this.create()}function n(){for(var a in k.requests)k.requests.hasOwnProperty(a)&&k.requests[a].abort()}var m=b(16),p=b(19),l=b(8),q=b(31),r=b(3)("engine.io-client:polling-xhr");f.exports=d;f.exports.Request=k;q(d,p);d.prototype.supportsBinary=!0;d.prototype.request=function(a){a=a||{};a.uri=this.uri();a.xd=this.xd;
a.xs=this.xs;a.agent=this.agent||!1;a.supportsBinary=this.supportsBinary;a.enablesXDR=this.enablesXDR;a.pfx=this.pfx;a.key=this.key;a.passphrase=this.passphrase;a.cert=this.cert;a.ca=this.ca;a.ciphers=this.ciphers;a.rejectUnauthorized=this.rejectUnauthorized;a.requestTimeout=this.requestTimeout;a.extraHeaders=this.extraHeaders;return new k(a)};d.prototype.doWrite=function(a,b){a=this.request({method:"POST",data:a,isBinary:"string"!==typeof a&&void 0!==a});var c=this;a.on("success",b);a.on("error",
function(a){c.onError("xhr post error",a)});this.sendXhr=a};d.prototype.doPoll=function(){r("xhr poll");var a=this.request(),b=this;a.on("data",function(a){b.onData(a)});a.on("error",function(a){b.onError("xhr poll error",a)});this.pollXhr=a};l(k.prototype);k.prototype.create=function(){var b={agent:this.agent,xdomain:this.xd,xscheme:this.xs,enablesXDR:this.enablesXDR};b.pfx=this.pfx;b.key=this.key;b.passphrase=this.passphrase;b.cert=this.cert;b.ca=this.ca;b.ciphers=this.ciphers;b.rejectUnauthorized=
this.rejectUnauthorized;var c=this.xhr=new m(b),d=this;try{r("xhr open %s: %s",this.method,this.uri);c.open(this.method,this.uri,this.async);try{if(this.extraHeaders){c.setDisableHeaderCheck&&c.setDisableHeaderCheck(!0);for(var h in this.extraHeaders)this.extraHeaders.hasOwnProperty(h)&&c.setRequestHeader(h,this.extraHeaders[h])}}catch(t){}if("POST"===this.method)try{this.isBinary?c.setRequestHeader("Content-type","application/octet-stream"):c.setRequestHeader("Content-type","text/plain;charset=UTF-8")}catch(t){}try{c.setRequestHeader("Accept",
"*/*")}catch(t){}"withCredentials"in c&&(c.withCredentials=!0);this.requestTimeout&&(c.timeout=this.requestTimeout);this.hasXDR()?(c.onload=function(){d.onLoad()},c.onerror=function(){d.onError(c.responseText)}):c.onreadystatechange=function(){if(2===c.readyState)try{var a=c.getResponseHeader("Content-Type");d.supportsBinary&&"application/octet-stream"===a&&(c.responseType="arraybuffer")}catch(v){}if(4===c.readyState)if(200===c.status||1223===c.status)d.onLoad();else setTimeout(function(){d.onError(c.status)},
0)};r("xhr data %s",this.data);c.send(this.data)}catch(t){setTimeout(function(){d.onError(t)},0);return}a.document&&(this.index=k.requestsCount++,k.requests[this.index]=this)};k.prototype.onSuccess=function(){this.emit("success");this.cleanup()};k.prototype.onData=function(a){this.emit("data",a);this.onSuccess()};k.prototype.onError=function(a){this.emit("error",a);this.cleanup(!0)};k.prototype.cleanup=function(b){if("undefined"!==typeof this.xhr&&null!==this.xhr){this.hasXDR()?this.xhr.onload=this.xhr.onerror=
c:this.xhr.onreadystatechange=c;if(b)try{this.xhr.abort()}catch(g){}a.document&&delete k.requests[this.index];this.xhr=null}};k.prototype.onLoad=function(){try{try{var a=this.xhr.getResponseHeader("Content-Type")}catch(w){}var b="application/octet-stream"===a?this.xhr.response||this.xhr.responseText:this.xhr.responseText}catch(w){this.onError(w)}if(null!=b)this.onData(b)};k.prototype.hasXDR=function(){return"undefined"!==typeof a.XDomainRequest&&!this.xs&&this.enablesXDR};k.prototype.abort=function(){this.cleanup()};
k.requestsCount=0;k.requests={};a.document&&(a.attachEvent?a.attachEvent("onunload",n):a.addEventListener&&a.addEventListener("beforeunload",n,!1))}).call(d,function(){return this}())},function(f,d,b){function a(a){var b=a&&a.forceBase64;if(!p||b)this.supportsBinary=!1;c.call(this,a)}var c=b(20),h=b(30),k=b(21);d=b(31);var n=b(32),m=b(3)("engine.io-client:polling");f.exports=a;var p=null!=(new (b(16))({xdomain:!1})).responseType;d(a,c);a.prototype.name="polling";a.prototype.doOpen=function(){this.poll()};
a.prototype.pause=function(a){function b(){m("paused");c.readyState="paused";a()}var c=this;this.readyState="pausing";if(this.polling||!this.writable){var d=0;this.polling&&(m("we are currently polling - waiting to pause"),d++,this.once("pollComplete",function(){m("pre-pause polling complete");--d||b()}));this.writable||(m("we are currently writing - waiting to pause"),d++,this.once("drain",function(){m("pre-pause writing complete");--d||b()}))}else b()};a.prototype.poll=function(){m("polling");this.polling=
!0;this.doPoll();this.emit("poll")};a.prototype.onData=function(a){var b=this;m("polling got data %s",a);k.decodePayload(a,this.socket.binaryType,function(a,c,d){if("opening"===b.readyState)b.onOpen();if("close"===a.type)return b.onClose(),!1;b.onPacket(a)});"closed"!==this.readyState&&(this.polling=!1,this.emit("pollComplete"),"open"===this.readyState?this.poll():m('ignoring poll - transport state "%s"',this.readyState))};a.prototype.doClose=function(){function a(){m("writing close packet");b.write([{type:"close"}])}
var b=this;"open"===this.readyState?(m("transport open - closing"),a()):(m("transport not open - deferring close"),this.once("open",a))};a.prototype.write=function(a){var b=this;this.writable=!1;var c=function(){b.writable=!0;b.emit("drain")};k.encodePayload(a,this.supportsBinary,function(a){b.doWrite(a,c)})};a.prototype.uri=function(){var a=this.query||{},b=this.secure?"https":"http",c="";!1!==this.timestampRequests&&(a[this.timestampParam]=n());this.supportsBinary||a.sid||(a.b64=1);a=h.encode(a);
this.port&&("https"===b&&443!==Number(this.port)||"http"===b&&80!==Number(this.port))&&(c=":"+this.port);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a}},function(f,d,b){function a(a){this.path=a.path;this.hostname=a.hostname;this.port=a.port;this.secure=a.secure;this.query=a.query;this.timestampParam=a.timestampParam;this.timestampRequests=a.timestampRequests;this.readyState="";this.agent=a.agent||!1;this.socket=a.socket;
this.enablesXDR=a.enablesXDR;this.pfx=a.pfx;this.key=a.key;this.passphrase=a.passphrase;this.cert=a.cert;this.ca=a.ca;this.ciphers=a.ciphers;this.rejectUnauthorized=a.rejectUnauthorized;this.forceNode=a.forceNode;this.extraHeaders=a.extraHeaders;this.localAddress=a.localAddress}var c=b(21);d=b(8);f.exports=a;d(a.prototype);a.prototype.onError=function(a,b){a=Error(a);a.type="TransportError";a.description=b;this.emit("error",a);return this};a.prototype.open=function(){if("closed"===this.readyState||
""===this.readyState)this.readyState="opening",this.doOpen();return this};a.prototype.close=function(){if("opening"===this.readyState||"open"===this.readyState)this.doClose(),this.onClose();return this};a.prototype.send=function(a){if("open"===this.readyState)this.write(a);else throw Error("Transport not open");};a.prototype.onOpen=function(){this.readyState="open";this.writable=!0;this.emit("open")};a.prototype.onData=function(a){a=c.decodePacket(a,this.socket.binaryType);this.onPacket(a)};a.prototype.onPacket=
function(a){this.emit("packet",a)};a.prototype.onClose=function(){this.readyState="closed";this.emit("close")}},function(f,d,b){(function(a){function c(a,b,c){if(!b)return d.encodeBase64Packet(a,c);var e=new FileReader;e.onload=function(){a.data=e.result;d.encodePacket(a,b,!0,c)};return e.readAsArrayBuffer(a.data)}function f(a,b,c){var d=Array(a.length);c=p(a.length,c);for(var e=function(a,c,e){b(c,function(b,c){d[a]=c;e(b,d)})},g=0;g<a.length;g++)e(g,a[g],c)}var k=b(22),n=b(23),m=b(24),p=b(25),l=
b(26),q;a&&a.ArrayBuffer&&(q=b(28));var r="undefined"!==typeof navigator&&/Android/i.test(navigator.userAgent),e="undefined"!==typeof navigator&&/PhantomJS/i.test(navigator.userAgent),g=r||e;d.protocol=3;var w=d.packets={open:0,close:1,ping:2,pong:3,message:4,upgrade:5,noop:6},x=k(w),t={type:"error",data:"parser error"},v=b(29);d.encodePacket=function(b,e,f,h){"function"===typeof e&&(h=e,e=!1);"function"===typeof f&&(h=f,f=null);var u=void 0===b.data?void 0:b.data.buffer||b.data;if(a.ArrayBuffer&&
u instanceof ArrayBuffer){if(e){f=b.data;e=new Uint8Array(f);f=new Uint8Array(1+f.byteLength);f[0]=w[b.type];for(b=0;b<e.length;b++)f[b+1]=e[b];b=h(f.buffer)}else b=d.encodeBase64Packet(b,h);return b}if(v&&u instanceof a.Blob)return e?g?b=c(b,e,h):(e=new Uint8Array(1),e[0]=w[b.type],b=new v([e.buffer,b.data]),b=h(b)):b=d.encodeBase64Packet(b,h),b;if(u&&u.base64)return h("b"+d.packets[b.type]+b.data.data);e=w[b.type];void 0!==b.data&&(e+=f?l.encode(String(b.data),{strict:!1}):String(b.data));return h(""+
e)};d.encodeBase64Packet=function(b,c){var e="b"+d.packets[b.type];if(v&&b.data instanceof a.Blob){var g=new FileReader;g.onload=function(){var a=g.result.split(",")[1];c(e+a)};return g.readAsDataURL(b.data)}try{var f=String.fromCharCode.apply(null,new Uint8Array(b.data))}catch(B){b=new Uint8Array(b.data);f=Array(b.length);for(var h=0;h<b.length;h++)f[h]=b[h];f=String.fromCharCode.apply(null,f)}e+=a.btoa(f);return c(e)};d.decodePacket=function(a,b,c){if(void 0===a)return t;if("string"===typeof a){if("b"===
a.charAt(0))return d.decodeBase64Packet(a.substr(1),b);if(c){a:{b=a;try{b=l.decode(b,{strict:!1})}catch(z){a=!1;break a}a=b}if(!1===a)return t}c=a.charAt(0);return Number(c)==c&&x[c]?1<a.length?{type:x[c],data:a.substring(1)}:{type:x[c]}:t}c=(new Uint8Array(a))[0];a=m(a,1);v&&"blob"===b&&(a=new v([a]));return{type:x[c],data:a}};d.decodeBase64Packet=function(a,b){var c=x[a.charAt(0)];if(!q)return{type:c,data:{base64:!0,data:a.substr(1)}};a=q.decode(a.substr(1));"blob"===b&&v&&(a=new v([a]));return{type:c,
data:a}};d.encodePayload=function(a,b,c){"function"===typeof b&&(c=b,b=null);var e=n(a);if(b&&e)return v&&!g?d.encodePayloadAsBlob(a,c):d.encodePayloadAsArrayBuffer(a,c);if(!a.length)return c("0:");f(a,function(a,c){d.encodePacket(a,e?b:!1,!1,function(a){c(null,a.length+":"+a)})},function(a,b){return c(b.join(""))})};d.decodePayload=function(a,b,c){if("string"!==typeof a)return d.decodePayloadAsBinary(a,b,c);"function"===typeof b&&(c=b,b=null);if(""===a)return c(t,0,1);var e="";for(var g,f,h=0,k=
a.length;h<k;h++)if(f=a.charAt(h),":"!==f)e+=f;else{if(""===e||e!=(g=Number(e)))return c(t,0,1);f=a.substr(h+1,g);if(e!=f.length)return c(t,0,1);if(f.length){e=d.decodePacket(f,b,!1);if(t.type===e.type&&t.data===e.data)return c(t,0,1);if(!1===c(e,h+g,k))return}h+=g;e=""}if(""!==e)return c(t,0,1)};d.encodePayloadAsArrayBuffer=function(a,b){if(!a.length)return b(new ArrayBuffer(0));f(a,function(a,b){d.encodePacket(a,!0,!0,function(a){return b(null,a)})},function(a,c){a=c.reduce(function(a,b){b="string"===
typeof b?b.length:b.byteLength;return a+b.toString().length+b+2},0);var d=new Uint8Array(a),e=0;c.forEach(function(a){var b="string"===typeof a,c=a;if(b){c=new Uint8Array(a.length);for(var g=0;g<a.length;g++)c[g]=a.charCodeAt(g);c=c.buffer}b?d[e++]=0:d[e++]=1;a=c.byteLength.toString();for(g=0;g<a.length;g++)d[e++]=parseInt(a[g]);d[e++]=255;c=new Uint8Array(c);for(g=0;g<c.length;g++)d[e++]=c[g]});return b(d.buffer)})};d.encodePayloadAsBlob=function(a,b){f(a,function(a,b){d.encodePacket(a,!0,!0,function(a){var c=
new Uint8Array(1);c[0]=1;if("string"===typeof a){for(var d=new Uint8Array(a.length),e=0;e<a.length;e++)d[e]=a.charCodeAt(e);a=d.buffer;c[0]=0}d=(a instanceof ArrayBuffer?a.byteLength:a.size).toString();var g=new Uint8Array(d.length+1);for(e=0;e<d.length;e++)g[e]=parseInt(d[e]);g[d.length]=255;v&&(a=new v([c.buffer,g.buffer,a]),b(null,a))})},function(a,c){return b(new v(c))})};d.decodePayloadAsBinary=function(a,b,c){"function"===typeof b&&(c=b,b=null);for(var e=[];0<a.byteLength;){for(var g=new Uint8Array(a),
f=0===g[0],h="",k=1;255!==g[k];k++){if(310<h.length)return c(t,0,1);h+=g[k]}a=m(a,2+h.length);h=parseInt(h);g=m(a,0,h);if(f)try{g=String.fromCharCode.apply(null,new Uint8Array(g))}catch(C){for(f=new Uint8Array(g),g="",k=0;k<f.length;k++)g+=String.fromCharCode(f[k])}e.push(g);a=m(a,h)}var p=e.length;e.forEach(function(a,e){c(d.decodePacket(a,b,!0),e,p)})}}).call(d,function(){return this}())},function(f,d){f.exports=Object.keys||function(b){var a=[],c=Object.prototype.hasOwnProperty,d;for(d in b)c.call(b,
d)&&a.push(d);return a}},function(f,d,b){(function(a){function c(b){if(!b||"object"!==typeof b)return!1;if(d(b)){for(var f=0,h=b.length;f<h;f++)if(c(b[f]))return!0;return!1}if("function"===typeof a.Buffer&&a.Buffer.isBuffer&&a.Buffer.isBuffer(b)||"function"===typeof a.ArrayBuffer&&b instanceof ArrayBuffer||n&&b instanceof Blob||m&&b instanceof File)return!0;if(b.toJSON&&"function"===typeof b.toJSON&&1===arguments.length)return c(b.toJSON(),!0);for(f in b)if(Object.prototype.hasOwnProperty.call(b,
f)&&c(b[f]))return!0;return!1}var d=b(10),k=Object.prototype.toString,n="function"===typeof a.Blob||"[object BlobConstructor]"===k.call(a.Blob),m="function"===typeof a.File||"[object FileConstructor]"===k.call(a.File);f.exports=c}).call(d,function(){return this}())},function(f,d){f.exports=function(b,a,c){var d=b.byteLength;a=a||0;c=c||d;if(b.slice)return b.slice(a,c);0>a&&(a+=d);0>c&&(c+=d);c>d&&(c=d);if(a>=d||a>=c||0===d)return new ArrayBuffer(0);b=new Uint8Array(b);d=new Uint8Array(c-a);for(var f=
0;a<c;a++,f++)d[f]=b[a];return d.buffer}},function(f,d){function b(){}f.exports=function(a,c,d){function f(a,b){if(0>=f.count)throw Error("after called too many times");--f.count;a?(h=!0,c(a),c=d):0!==f.count||h||c(null,b)}var h=!1;d=d||b;f.count=a;return 0===a?c():f}},function(f,d,b){var a;(function(b,d){(function(c){function d(a){for(var b=[],c=0,d=a.length,e,g;c<d;)e=a.charCodeAt(c++),55296<=e&&56319>=e&&c<d?(g=a.charCodeAt(c++),56320==(g&64512)?b.push(((e&1023)<<10)+(g&1023)+65536):(b.push(e),
c--)):b.push(e);return b}function f(a,b){if(55296<=a&&57343>=a){if(b)throw Error("Lone surrogate U+"+a.toString(16).toUpperCase()+" is not a scalar value");return!1}return!0}function h(){if(g>=e)throw Error("Invalid byte index");var a=r[g]&255;g++;if(128==(a&192))return a&63;throw Error("Invalid continuation byte");}function k(a){if(g>e)throw Error("Invalid byte index");if(g==e)return!1;var b=r[g]&255;g++;if(0==(b&128))return b;if(192==(b&224)){var c=h();b=(b&31)<<6|c;if(128<=b)return b;throw Error("Invalid continuation byte");
}if(224==(b&240)){c=h();var d=h();b=(b&15)<<12|c<<6|d;if(2048<=b)return f(b,a)?b:65533;throw Error("Invalid continuation byte");}if(240==(b&248)&&(c=h(),d=h(),a=h(),b=(b&7)<<18|c<<12|d<<6|a,65536<=b&&1114111>=b))return b;throw Error("Invalid UTF-8 detected");}var q=String.fromCharCode,r,e,g;!(a={version:"2.1.2",encode:function(a,b){b=b||{};b=!1!==b.strict;a=d(a);for(var c=a.length,e=-1,g,h="";++e<c;){g=a[e];var k=b;if(0==(g&4294967168))g=q(g);else{var l="";0==(g&4294965248)?l=q(g>>6&31|192):0==(g&
4294901760)?(f(g,k)||(g=65533),l=q(g>>12&15|224),l+=q(g>>6&63|128)):0==(g&4292870144)&&(l=q(g>>18&7|240),l+=q(g>>12&63|128),l+=q(g>>6&63|128));g=l+=q(g&63|128)}h+=g}return h},decode:function(a,b){b=b||{};b=!1!==b.strict;r=d(a);e=r.length;g=0;a=[];for(var c;!1!==(c=k(b));)a.push(c);b=a.length;c=-1;for(var f,h="";++c<b;)f=a[c],65535<f&&(f-=65536,h+=q(f>>>10&1023|55296),f=56320|f&1023),h+=q(f);return h}},void 0!==a&&(b.exports=a))})(this)}).call(d,b(27)(f),function(){return this}())},function(f,d){f.exports=
function(b){b.webpackPolyfill||(b.deprecate=function(){},b.paths=[],b.children=[],b.webpackPolyfill=1);return b}},function(f,d){(function(){for(var b=new Uint8Array(256),a=0;64>a;a++)b["ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charCodeAt(a)]=a;d.encode=function(a){a=new Uint8Array(a);var b,c=a.length,d="";for(b=0;b<c;b+=3)d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a[b]>>2],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(a[b]&
3)<<4|a[b+1]>>4],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[(a[b+1]&15)<<2|a[b+2]>>6],d+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"[a[b+2]&63];2===c%3?d=d.substring(0,d.length-1)+"=":1===c%3&&(d=d.substring(0,d.length-2)+"==");return d};d.decode=function(a){var c=.75*a.length,d=a.length,f=0;"="===a[a.length-1]&&(c--,"="===a[a.length-2]&&c--);var m=new ArrayBuffer(c),p=new Uint8Array(m);for(c=0;c<d;c+=4){var l=b[a.charCodeAt(c)];var q=b[a.charCodeAt(c+
1)];var r=b[a.charCodeAt(c+2)];var e=b[a.charCodeAt(c+3)];p[f++]=l<<2|q>>4;p[f++]=(q&15)<<4|r>>2;p[f++]=(r&3)<<6|e&63}return m}})()},function(f,d){(function(b){function a(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.buffer instanceof ArrayBuffer){var d=c.buffer;if(c.byteLength!==d.byteLength){var g=new Uint8Array(c.byteLength);g.set(new Uint8Array(d,c.byteOffset,c.byteLength));d=g.buffer}a[b]=d}}}function c(b,c){c=c||{};var d=new k;a(b);for(var e=0;e<b.length;e++)d.append(b[e]);return c.type?d.getBlob(c.type):
d.getBlob()}function d(b,c){a(b);return new Blob(b,c||{})}var k=b.BlobBuilder||b.WebKitBlobBuilder||b.MSBlobBuilder||b.MozBlobBuilder;try{var n=2===(new Blob(["hi"])).size}catch(l){n=!1}var m;if(m=n)try{m=2===(new Blob([new Uint8Array([1,2])])).size}catch(l){m=!1}var p=k&&k.prototype.append&&k.prototype.getBlob;b=n?m?b.Blob:d:p?c:void 0;f.exports=b}).call(d,function(){return this}())},function(f,d){d.encode=function(b){var a="",c;for(c in b)b.hasOwnProperty(c)&&(a.length&&(a+="&"),a+=encodeURIComponent(c)+
"="+encodeURIComponent(b[c]));return a};d.decode=function(b){var a={};b=b.split("&");for(var c=0,d=b.length;c<d;c++){var f=b[c].split("=");a[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}return a}},function(f,d){f.exports=function(b,a){var c=function(){};c.prototype=a.prototype;b.prototype=new c;b.prototype.constructor=b}},function(f,d){function b(a){var b="";do b=c[a%64]+b,a=Math.floor(a/64);while(0<a);return b}function a(){var a=b(+new Date);return a!==m?(k=0,m=a):a+"."+b(k++)}for(var c="0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz-_".split(""),
h={},k=0,n=0,m;64>n;n++)h[c[n]]=n;a.encode=b;a.decode=function(a){var b=0;for(n=0;n<a.length;n++)b=64*b+h[a.charAt(n)];return b};f.exports=a},function(f,d,b){(function(a){function c(){}function d(b){k.call(this,b);this.query=this.query||{};l||(a.___eio||(a.___eio=[]),l=a.___eio);this.index=l.length;var d=this;l.push(function(a){d.onData(a)});this.query.j=this.index;a.document&&a.addEventListener&&a.addEventListener("beforeunload",function(){d.script&&(d.script.onerror=c)},!1)}var k=b(19),n=b(31);
f.exports=d;var m=/\n/g,p=/\\n/g,l;n(d,k);d.prototype.supportsBinary=!1;d.prototype.doClose=function(){this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);this.form&&(this.form.parentNode.removeChild(this.form),this.iframe=this.form=null);k.prototype.doClose.call(this)};d.prototype.doPoll=function(){var a=this,b=document.createElement("script");this.script&&(this.script.parentNode.removeChild(this.script),this.script=null);b.async=!0;b.src=this.uri();b.onerror=function(b){a.onError("jsonp poll error",
b)};var c=document.getElementsByTagName("script")[0];c?c.parentNode.insertBefore(b,c):(document.head||document.body).appendChild(b);this.script=b;"undefined"!==typeof navigator&&/gecko/i.test(navigator.userAgent)&&setTimeout(function(){var a=document.createElement("iframe");document.body.appendChild(a);document.body.removeChild(a)},100)};d.prototype.doWrite=function(a,b){function c(){d();b()}function d(){if(f.iframe)try{f.form.removeChild(f.iframe)}catch(y){f.onError("jsonp polling iframe removal error",
y)}try{n=document.createElement('<iframe src="javascript:0" name="'+f.iframeId+'">')}catch(y){n=document.createElement("iframe"),n.name=f.iframeId,n.src="javascript:0"}n.id=f.iframeId;f.form.appendChild(n);f.iframe=n}var f=this;if(!this.form){var h=document.createElement("form"),k=document.createElement("textarea"),l=this.iframeId="eio_iframe_"+this.index,n;h.className="socketio";h.style.position="absolute";h.style.top="-1000px";h.style.left="-1000px";h.target=l;h.method="POST";h.setAttribute("accept-charset",
"utf-8");k.name="d";h.appendChild(k);document.body.appendChild(h);this.form=h;this.area=k}this.form.action=this.uri();d();a=a.replace(p,"\\\n");this.area.value=a.replace(m,"\\n");try{this.form.submit()}catch(y){}this.iframe.attachEvent?this.iframe.onreadystatechange=function(){"complete"===f.iframe.readyState&&c()}:this.iframe.onload=c}}).call(d,function(){return this}())},function(f,d,b){(function(a){function c(a){a&&a.forceBase64&&(this.supportsBinary=!1);this.perMessageDeflate=a.perMessageDeflate;
this.usingBrowserWebSocket=q&&!a.forceNode;this.protocols=a.protocols;this.usingBrowserWebSocket||(e=r);d.call(this,a)}var d=b(20),k=b(21),n=b(30),m=b(31),p=b(32),l=b(3)("engine.io-client:websocket"),q=a.WebSocket||a.MozWebSocket;if("undefined"===typeof window)try{var r=b(35)}catch(g){}var e=q;e||"undefined"!==typeof window||(e=r);f.exports=c;m(c,d);c.prototype.name="websocket";c.prototype.supportsBinary=!0;c.prototype.doOpen=function(){if(this.check()){var a=this.uri(),b=this.protocols,c={agent:this.agent,
perMessageDeflate:this.perMessageDeflate};c.pfx=this.pfx;c.key=this.key;c.passphrase=this.passphrase;c.cert=this.cert;c.ca=this.ca;c.ciphers=this.ciphers;c.rejectUnauthorized=this.rejectUnauthorized;this.extraHeaders&&(c.headers=this.extraHeaders);this.localAddress&&(c.localAddress=this.localAddress);try{this.ws=this.usingBrowserWebSocket?b?new e(a,b):new e(a):new e(a,b,c)}catch(t){return this.emit("error",t)}void 0===this.ws.binaryType&&(this.supportsBinary=!1);this.ws.supports&&this.ws.supports.binary?
(this.supportsBinary=!0,this.ws.binaryType="nodebuffer"):this.ws.binaryType="arraybuffer";this.addEventListeners()}};c.prototype.addEventListeners=function(){var a=this;this.ws.onopen=function(){a.onOpen()};this.ws.onclose=function(){a.onClose()};this.ws.onmessage=function(b){a.onData(b.data)};this.ws.onerror=function(b){a.onError("websocket error",b)}};c.prototype.write=function(b){function c(){d.emit("flush");setTimeout(function(){d.writable=!0;d.emit("drain")},0)}var d=this;this.writable=!1;for(var e=
b.length,f=0,g=e;f<g;f++)(function(b){k.encodePacket(b,d.supportsBinary,function(f){if(!d.usingBrowserWebSocket){var g={};b.options&&(g.compress=b.options.compress);d.perMessageDeflate&&("string"===typeof f?a.Buffer.byteLength(f):f.length)<d.perMessageDeflate.threshold&&(g.compress=!1)}try{d.usingBrowserWebSocket?d.ws.send(f):d.ws.send(f,g)}catch(A){l("websocket closed before onclose event")}--e||c()})})(b[f])};c.prototype.onClose=function(){d.prototype.onClose.call(this)};c.prototype.doClose=function(){"undefined"!==
typeof this.ws&&this.ws.close()};c.prototype.uri=function(){var a=this.query||{},b=this.secure?"wss":"ws",c="";this.port&&("wss"===b&&443!==Number(this.port)||"ws"===b&&80!==Number(this.port))&&(c=":"+this.port);this.timestampRequests&&(a[this.timestampParam]=p());this.supportsBinary||(a.b64=1);a=n.encode(a);a.length&&(a="?"+a);var d=-1!==this.hostname.indexOf(":");return b+"://"+(d?"["+this.hostname+"]":this.hostname)+c+this.path+a};c.prototype.check=function(){return!!e&&!("__initialize"in e&&this.name===
c.prototype.name)}}).call(d,function(){return this}())},function(f,d){},function(f,d){var b=[].indexOf;f.exports=function(a,c){if(b)return a.indexOf(c);for(var d=0;d<a.length;++d)if(a[d]===c)return d;return-1}},function(f,d,b){function a(a,b,c){this.io=a;this.nsp=b;this.json=this;this.ids=0;this.acks={};this.receiveBuffer=[];this.sendBuffer=[];this.connected=!1;this.disconnected=!0;this.flags={};c&&c.query&&(this.query=c.query);this.io.autoConnect&&this.open()}var c="function"===typeof Symbol&&"symbol"===
typeof Symbol.iterator?function(a){return typeof a}:function(a){return a&&"function"===typeof Symbol&&a.constructor===Symbol&&a!==Symbol.prototype?"symbol":typeof a},h=b(7);d=b(8);var k=b(38),n=b(39),m=b(40),p=b(3)("socket.io-client:socket"),l=b(30),q=b(23);f.exports=a;var r={connect:1,connect_error:1,connect_timeout:1,connecting:1,disconnect:1,error:1,reconnect:1,reconnect_attempt:1,reconnect_failed:1,reconnect_error:1,reconnecting:1,ping:1,pong:1},e=d.prototype.emit;d(a.prototype);a.prototype.subEvents=
function(){if(!this.subs){var a=this.io;this.subs=[n(a,"open",m(this,"onopen")),n(a,"packet",m(this,"onpacket")),n(a,"close",m(this,"onclose"))]}};a.prototype.open=a.prototype.connect=function(){if(this.connected)return this;this.subEvents();this.io.open();if("open"===this.io.readyState)this.onopen();this.emit("connecting");return this};a.prototype.send=function(){var a=k(arguments);a.unshift("message");this.emit.apply(this,a);return this};a.prototype.emit=function(a){if(r.hasOwnProperty(a))return e.apply(this,
arguments),this;var b=k(arguments),c={type:(void 0!==this.flags.binary?this.flags.binary:q(b))?h.BINARY_EVENT:h.EVENT,data:b,options:{}};c.options.compress=!this.flags||!1!==this.flags.compress;"function"===typeof b[b.length-1]&&(p("emitting packet with ack id %d",this.ids),this.acks[this.ids]=b.pop(),c.id=this.ids++);this.connected?this.packet(c):this.sendBuffer.push(c);this.flags={};return this};a.prototype.packet=function(a){a.nsp=this.nsp;this.io.packet(a)};a.prototype.onopen=function(){p("transport is open - connecting");
if("/"!==this.nsp)if(this.query){var a="object"===c(this.query)?l.encode(this.query):this.query;p("sending connect packet with query %s",a);this.packet({type:h.CONNECT,query:a})}else this.packet({type:h.CONNECT})};a.prototype.onclose=function(a){p("close (%s)",a);this.connected=!1;this.disconnected=!0;delete this.id;this.emit("disconnect",a)};a.prototype.onpacket=function(a){var b=a.type===h.ERROR&&"/"===a.nsp;if(a.nsp===this.nsp||b)switch(a.type){case h.CONNECT:this.onconnect();break;case h.EVENT:this.onevent(a);
break;case h.BINARY_EVENT:this.onevent(a);break;case h.ACK:this.onack(a);break;case h.BINARY_ACK:this.onack(a);break;case h.DISCONNECT:this.ondisconnect();break;case h.ERROR:this.emit("error",a.data)}};a.prototype.onevent=function(a){var b=a.data||[];p("emitting event %j",b);null!=a.id&&(p("attaching ack callback to event"),b.push(this.ack(a.id)));this.connected?e.apply(this,b):this.receiveBuffer.push(b)};a.prototype.ack=function(a){var b=this,c=!1;return function(){if(!c){c=!0;var d=k(arguments);
p("sending ack %j",d);b.packet({type:q(d)?h.BINARY_ACK:h.ACK,id:a,data:d})}}};a.prototype.onack=function(a){var b=this.acks[a.id];"function"===typeof b?(p("calling ack %s with %j",a.id,a.data),b.apply(this,a.data),delete this.acks[a.id]):p("bad ack %s",a.id)};a.prototype.onconnect=function(){this.connected=!0;this.disconnected=!1;this.emit("connect");this.emitBuffered()};a.prototype.emitBuffered=function(){var a;for(a=0;a<this.receiveBuffer.length;a++)e.apply(this,this.receiveBuffer[a]);this.receiveBuffer=
[];for(a=0;a<this.sendBuffer.length;a++)this.packet(this.sendBuffer[a]);this.sendBuffer=[]};a.prototype.ondisconnect=function(){p("server disconnect (%s)",this.nsp);this.destroy();this.onclose("io server disconnect")};a.prototype.destroy=function(){if(this.subs){for(var a=0;a<this.subs.length;a++)this.subs[a].destroy();this.subs=null}this.io.destroy(this)};a.prototype.close=a.prototype.disconnect=function(){this.connected&&(p("performing disconnect (%s)",this.nsp),this.packet({type:h.DISCONNECT}));
this.destroy();if(this.connected)this.onclose("io client disconnect");return this};a.prototype.compress=function(a){this.flags.compress=a;return this};a.prototype.binary=function(a){this.flags.binary=a;return this}},function(f,d){f.exports=function(b,a){for(var c=[],d=(a=a||0)||0;d<b.length;d++)c[d-a]=b[d];return c}},function(f,d){f.exports=function(b,a,c){b.on(a,c);return{destroy:function(){b.removeListener(a,c)}}}},function(f,d){var b=[].slice;f.exports=function(a,c){"string"==typeof c&&(c=a[c]);
if("function"!=typeof c)throw Error("bind() requires a function");var d=b.call(arguments,2);return function(){return c.apply(a,d.concat(b.call(arguments)))}}},function(f,d){function b(a){a=a||{};this.ms=a.min||100;this.max=a.max||1E4;this.factor=a.factor||2;this.jitter=0<a.jitter&&1>=a.jitter?a.jitter:0;this.attempts=0}f.exports=b;b.prototype.duration=function(){var a=this.ms*Math.pow(this.factor,this.attempts++);if(this.jitter){var b=Math.random(),d=Math.floor(b*this.jitter*a);a=0==(Math.floor(10*
b)&1)?a-d:a+d}return Math.min(a,this.max)|0};b.prototype.reset=function(){this.attempts=0};b.prototype.setMin=function(a){this.ms=a};b.prototype.setMax=function(a){this.max=a};b.prototype.setJitter=function(a){this.jitter=a}}])});
